from collections.abc import Callable

import altair as alt
import pandera.polars as pa
import polars as pl

# I don't want to have to write all the simulation running code every time

SimulateFunction = Callable[[int, int], pl.DataFrame]

sim_schema = pa.DataFrameSchema(
    columns={"estimand": pa.Column(str), "value": pa.Column(float)}, strict=True
)


def iterate_samples(
    sim: SimulateFunction,
    n_sizes: int = 5,
    n_seeds: int = 10,
    start_order: int = 2,
    seed_offset: int = 12345,
) -> pl.DataFrame:
    """Iterate over generated samples.

    Args:
        sim: SimulateFunction returning a single comparison DataFrame for iteration
            DataFrame must consist of an "estimand" column
               and a "value" column containing the value of interest
        n_sizes: number of orders of magnitude for size.
        n_seeds: number of seeds for sample generation
        start_order: at which order of magnitude to start sizes. Defaults to 2 (for 100)
        seed_offset: starting offset for seeds

    Returns:
        pl.DataFrame with combined results per iteration
    """  # noqa: E501
    assert n_seeds > 1, f"n_seeds must be greater than 1, got {n_seeds}"

    def get_sims(size: int) -> pl.DataFrame:
        seeds = [seed_offset + n for n in range(n_seeds)]

        return (
            pl.concat([sim_schema.validate(sim(size, seed)) for seed in seeds])
            .group_by("estimand")
            .agg(
                pl.col("value").mean().alias("mean"),
                pl.col("value").std().alias("std"),
            )
            .with_columns(
                (pl.col("mean") - pl.col("std")).alias("mean - std"),
                (pl.col("mean") + pl.col("std")).alias("mean + std"),
                size=pl.lit(size),
            )
        )

    assert n_sizes >= 1, f"n_sizes must be >= 1, got {n_sizes} "

    def get_sizes() -> pl.DataFrame:
        sizes = [10**n for n in range(start_order, start_order + n_sizes)]
        return pl.concat([get_sims(s) for s in sizes])

    return get_sizes()


def plot_samples(data: pl.DataFrame) -> alt.LayerChart:
    """Plot data generated by iterate_samples()."""
    base = (
        alt.Chart(data)
        .encode(
            alt.X("size").scale(type="log").title("Sample size"),
            alt.Color(
                "estimand",
                legend=alt.Legend(
                    labelLimit=0, orient="bottom", direction="vertical"
                ),
            ),
        )
        .properties(width=600, height=300)
    )

    max_ = data.select(pl.col("mean + std").max()).item()

    mean = base.mark_line(interpolate="monotone").encode(alt.Y("mean:Q").title(None))
    uncertainty = base.mark_area(
        opacity=0.2, interpolate="monotone", clip=True
    ).encode(
        alt.Y("mean - std:Q").scale(domain=(0, max_)),
        alt.Y2("mean + std:Q"),
    )

    return uncertainty + mean
